"use client"
import Link from "next/link"
import { useEffect, useState } from "react"

type Payload = { set?: string | number | null; value?: string | number | null; twoD?: string | null; collectedAt?: string | null; status?: { state: "WAITING" | "LIVE" | "CLOSED"; nextSession?: { label: string } } }
const slots = [["11:00 AM", "morning"], ["12:00 PM", "morning-close"], ["3:00 PM", "afternoon"], ["4:30 PM", "afternoon-close"]]
export default function Home() {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState("")
  useEffect(() => { let active = true; const load = async () => { try { const r = await fetch("/api/2d/latest", { cache: "no-store" }); if (!r.ok) throw new Error("Our market service is unavailable."); const next = await r.json(); if (active) { setData(next); setError("") } } catch (e) { if (active) setError(e instanceof Error ? e.message : "Unable to load market data.") } }; load(); const timer = setInterval(load, 15000); return () => { active = false; clearInterval(timer) } }, [])
  const state = data?.status?.state || "WAITING"; const stale = data?.collectedAt ? Date.now() - Date.parse(data.collectedAt) > 120000 : false
  return <main className="mx-auto min-h-screen max-w-md px-3 pb-8"><header className="pt-8 text-center"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#806b43]">Myanmar 2D / 3D</p><div className="mt-4 flex items-center justify-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${state === "LIVE" ? "bg-green-100 text-green-800" : state === "CLOSED" ? "bg-amber-100 text-amber-900" : "bg-black/10 text-[#66583d]"}`}>{state}</span>{data?.collectedAt && <span className="text-xs text-[#806b43]">Updated {new Date(data.collectedAt).toLocaleTimeString()}</span>}</div><h1 className="txet-sh mt-2 text-8xl font-semibold">{state === "LIVE" ? data?.twoD || "--" : "--"}</h1><p className="text-sm text-[#66583d]">{state === "LIVE" ? "Live from SET market data" : state === "CLOSED" ? `Market closed. Next session starts at ${data?.status?.nextSession?.label || "11:00 AM"}` : `Next session starts at ${data?.status?.nextSession?.label || "11:00 AM"}`}</p></header>{error && <div role="alert" className="mt-4 rounded-xl bg-red-100 px-4 py-3 text-center text-sm text-red-800">{error}</div>}{!error && !data && <div className="mt-4 rounded-xl bg-white/70 px-4 py-3 text-center text-sm">Loading latest market data...</div>}{stale && <div role="status" className="mt-4 rounded-xl bg-amber-100 px-4 py-3 text-center text-sm text-amber-900">Data is stale. Waiting for the next SET update.</div>}<nav className="mt-6 grid grid-cols-2 gap-2 text-center text-sm"><Link className="rounded-xl bg-white/75 px-3 py-3 font-semibold" href="/2d-results">2D History</Link><Link className="rounded-xl bg-white/75 px-3 py-3 font-semibold" href="/3d-results">3D Results</Link></nav><section className="mt-3 space-y-2" aria-label="Today's sessions">{slots.map(([time, key]) => <article className="filter-div rounded-xl bg-white/75 px-4 py-3" key={key}><div className="flex justify-between text-sm"><span>{time}</span><strong>{key.includes("close") ? "CLOSED" : state === "LIVE" ? data?.twoD || "--" : "--"}</strong></div><div className="mt-1 flex justify-between text-xs text-[#806b43]"><span>SET {key.includes("close") ? "--" : data?.set || "--"}</span><span>{key.includes("close") ? "Final result" : data?.value || "Waiting"}</span></div></article>)}</section></main>
}
